# Generated by Django 4.2.11 on 2025-10-13 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('branches', '0001_initial'),
        ('supervisors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_type', models.CharField(choices=[('clinical', 'Clinical'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('administrative', 'Administrative'), ('other', 'Other')], default='clinical', max_length=32)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='interns/profile_photos/')),
                ('application_letter', models.FileField(blank=True, null=True, upload_to='interns/application_letters/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=128)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_supervisor', models.ForeignKey(blank=True, help_text="Academic supervisor associated with the intern's school.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.academicsupervisor')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('internal_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interns', to='supervisors.employeeprofile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intern Profile',
                'verbose_name_plural': 'Intern Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
