# Generated by Django 4.2.11 on 2025-10-27 20:50

from django.db import migrations, models
import django.db.models.deletion


def populate_intern_types(apps, schema_editor):
    InternType = apps.get_model('interns', 'InternType')
    InternProfile = apps.get_model('interns', 'InternProfile')
    
    # Create InternType instances
    types_data = [
        ('clinical', 'Clinical'),
        ('nursing', 'Nursing'),
        ('pharmacy', 'Pharmacy'),
        ('laboratory', 'Laboratory'),
        ('administrative', 'Administrative'),
        ('other', 'Other'),
    ]
    
    for name, display_name in types_data:
        InternType.objects.get_or_create(name=name, defaults={'display_name': display_name})
    
    # Update InternProfile records
    for profile in InternProfile.objects.filter(intern_type__isnull=False):
        try:
            intern_type_obj = InternType.objects.get(name=profile.intern_type)
            profile.intern_type_new_id = intern_type_obj.id
            profile.save(update_fields=['intern_type_new_id'])
        except InternType.DoesNotExist:
            pass  # Skip if type doesn't exist


def reverse_populate_intern_types(apps, schema_editor):
    InternType = apps.get_model('interns', 'InternType')
    InternProfile = apps.get_model('interns', 'InternProfile')
    
    # Update InternProfile records back to string values
    for profile in InternProfile.objects.filter(intern_type_new_id__isnull=False):
        try:
            intern_type_obj = profile.intern_type_new
            profile.intern_type = intern_type_obj.name
            profile.save(update_fields=['intern_type'])
        except:
            pass
    
    # Delete InternType instances
    InternType.objects.filter(name__in=['clinical', 'nursing', 'pharmacy', 'laboratory', 'administrative', 'other']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Intern Type',
                'verbose_name_plural': 'Intern Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='internprofile',
            name='intern_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interns.interntype'),
        ),
        migrations.RunPython(
            populate_intern_types,
            reverse_code=reverse_populate_intern_types,
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='intern_type',
        ),
        migrations.RenameField(
            model_name='internprofile',
            old_name='intern_type_new',
            new_name='intern_type',
        ),
    ]
