# Generated by Django 4.2.11 on 2025-10-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_full_day', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='When blank, holiday applies to all branches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='branches.branch')),
            ],
            options={
                'ordering': ['date', 'name'],
                'unique_together': {('branch', 'date', 'name')},
            },
        ),
    ]
