# Generated by Django 4.2.11 on 2025-10-13 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisors', '0001_initial'),
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('week_number', models.PositiveIntegerField(help_text='Week number within the internship schedule.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=32)),
                ('supervisor_score', models.PositiveIntegerField(blank=True, help_text='Supervisor score out of 100.', null=True)),
                ('supervisor_note', models.TextField(blank=True)),
                ('intern_score', models.PositiveIntegerField(blank=True, help_text='Intern self-assessment score out of 100.', null=True)),
                ('intern_note', models.TextField(blank=True, help_text='Intern self-assessment reflection shared with the supervisor.')),
                ('acknowledgement_note', models.TextField(blank=True, help_text='Optional closing remarks recorded upon completion of assessment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_assessments', to='supervisors.employeeprofile')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='interns.internprofile')),
            ],
            options={
                'ordering': ['-assessment_date', 'intern__user__last_name'],
                'unique_together': {('intern', 'week_number')},
            },
        ),
    ]
