# Generated by Django 4.2.11 on 2025-10-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_latitude_alter_attendance_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location_accuracy_m',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
