# Generated by Django 4.2.11 on 2025-10-14 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_attendance_approval', models.BooleanField(default=True, help_text='Send email when attendance is approved/rejected')),
                ('email_on_assessment_created', models.BooleanField(default=True, help_text='Send email when new assessment is created')),
                ('email_on_assessment_reviewed', models.BooleanField(default=True, help_text='Send email when assessment is reviewed')),
                ('email_on_absence_status', models.BooleanField(default=True, help_text='Send email when absence request status changes')),
                ('email_on_onboarding', models.BooleanField(default=True, help_text='Send email for onboarding events')),
                ('in_app_notifications', models.BooleanField(default=True, help_text='Show in-app notifications')),
                ('daily_digest', models.BooleanField(default=False, help_text='Receive daily digest of notifications')),
                ('weekly_digest', models.BooleanField(default=False, help_text='Receive weekly digest of notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the notification', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='Visual type of notification (info, success, warning, error)', max_length=20)),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('assessment', 'Assessment'), ('absenteeism', 'Absenteeism'), ('onboarding', 'Onboarding'), ('system', 'System'), ('general', 'General')], default='general', help_text='Category of notification for filtering', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('action_url', models.CharField(blank=True, help_text='Optional URL to navigate to when clicked', max_length=500)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether an email notification was sent')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the email was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the notification was last updated')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['category'], name='notificatio_categor_fd561f_idx')],
            },
        ),
    ]
